### PR TITLE
Updated README due to #17

### PR DESCRIPTION
**Pull request by edison**
Added example on how to push events using `.dataLayer()` function.

### CODE REVIEW

**Review by arfanliaqat — APPROVED** [review]

**Comment by tractorcow** [comment]
Thanks for this @edison ; These docs would have saved me a lot of effort if they were available earlier!

**Comment by edison** [comment]
Hey @alinemorelli, I think merge would be helpful for some people, based on @tractorcow experience and myself. Just some lines of docs, no risk. 😉

**Comment by arfanliaqat** [comment]
@edison unfortunately i have similar story to @tractorcow, thats why i reached this issue, and approved it :thinking: ... although i've no `write access` to this repo to merge this change :shrug: but i also think it should be merged :+1:

**Comment by igmrrf** [comment]
Hello @alinemorelli

**Pull request closed without merging**
