### PR TITLE
Add possibility to pass in a CSP nonce value

### LINKED ISSUE #41: Violation of Content Security Policy directive script-src that disables inline scripts
TagManager.js:59 appears to fail CSP directive that prevents inline scripts. https://github.com/alinemorelli/react-gtm/blob/52f2328ab1b45734c342e9021fe693795a03972d/dist/TagManager.js#L59

My Content-Security-Policy directive is:
`script-src 'self' https://*.googletagmanager.com https://*.googleapis.com https://*.google.com https://*.google-analytics.com https://*.gstatic.com;`

Google's console responds with:
`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://*.googletagmanager.com https://*.googleapis.com https://*.google.com https://*.google-analytics.com https://*.gstatic.com". Either the 'unsafe-inline' keyword, a hash ('sha256-AmDiJyvKvr94dB5Fpw4fKR7GDBqrf2xZhnMaV3YAPrA='), or a nonce ('nonce-...') is required to enable inline execution.`

I definitely can't allow 'unsafe-inline' in my app. Any ideas?

### PR DESCRIPTION
**Pull request by webjunkie**
Add nonce argument to pass in a CSP nonce value so that the script elements are allowed to run on CSP enabled sites.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script

Fixes #41

### CODE REVIEW

**Comment by jamesism** [comment]
Any chance this will merge soon?

**Comment by webjunkie** [comment]
I merged master to fix merge conflicts.

**Comment by nick4fake** [comment]
@alinemorelli could you please merge this?

**Comment by shekyb** [comment]
Can we expect this to be merged?

**Comment by roiekoper** [comment]
Any updates about this PR?

**Comment by TheMikeL** [comment]
Any updates on this PR, or any alternatives to adding nonce in this library?

**Comment by dazulu** [comment]
Are there any updates about this PR?

**Comment by dazulu** [comment]
Are there any updates about this PR?

**Comment by eugeniosegala** [comment]
We need to merge this PR.

How can I help to make this happen?

**Comment by webjunkie** [comment]
Fixed in https://github.com/mosesokemwa/react-gtm-updated/commit/eab2eb4adb9f8d9cfd73f3c387979428028915ea

**Pull request closed without merging**
